<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPeamxyn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPeamxyn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPeamxyn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPeamxyn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPeamxyn\appProdProjectContainer([
    'container.build_hash' => 'Peamxyn',
    'container.build_id' => 'f405cc0f',
    'container.build_time' => 1588995934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPeamxyn');
